<?php

$ap_uri = 'file://' . __DIR__ .  '/../../oerap.ttl#ap';
ApplicationProfile::add(
  $ap_uri, 'turtle', LDE_ENTITY_TYPE, 'ldf_field_type'
);

/**
 * Implements hook_menu().
 */
function oerworldmap_menu() {

  $items['oerworldmap'] = array(
    'title' => 'OER World Map',
    'page callback' => 'oerworldmap',
    'access callback' => true,
  );

  $items['oerworldmap/view'] = array(
    'title' => 'OER World Map',
    'page callback' => 'oerworldmap',
    'access callback' => true,
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );

  $items['oerworldmap/search'] = array(
    'title' => 'Search',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('oerworldmap_search'),
    'access callback' => true,
    'type' => MENU_LOCAL_TASK,
  );

  $ap = ApplicationProfile::get(LDE_ENTITY_TYPE);
  foreach ($ap->getTopBundles() as $bundle) {
    $items["oerworldmap/add/$bundle"] = array(
      'title' => "Add new $bundle",
      'page callback' => 'oerworldmap_resource_add',
      'page arguments' => array($bundle),
      'access callback' => true,
      'type' => MENU_LOCAL_TASK,
    );
  }

  $items['oerworldmap/proxy'] = array(
    'page callback' => 'oerworldmap_resource_proxy',
    'access callback' => true,
    'type' => MENU_CALLBACK,
  );

  return $items;

}

function oerworldmap() {
  drupal_set_title('');
  drupal_add_js(
    drupal_get_path('module', 'oerworldmap') . '/jquery.rdfquery.core-1.0.js'
  );
  drupal_add_js(
    'http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js', 'external'
  );
  drupal_add_css(
    'http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css', 'external'
  );
  drupal_add_js(
    'http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js', 'external'
  );
  drupal_add_js(array('oerworldmap' => array(
    'apiUrl' => variable_get('lde_api_host'),
    'basePath' => base_path() . drupal_get_path('module', 'oerworldmap'),
    'proxyUrl' => base_path() . 'oerworldmap/proxy?uri='
  )), 'setting');
  drupal_add_js(
    drupal_get_path('module', 'oerworldmap') . '/oerworldmap.js'
  );
  drupal_add_library('system', 'drupal.collapse');
  drupal_add_js(array('ldf' => array(
    'basePath' => base_path() . drupal_get_path('module', 'ldf')
  )), 'setting');
  drupal_add_js(
    drupal_get_path('module', 'ldf') . '/ldf.js'
  );
  return array(
    '#type' => 'markup',
    '#markup' => '<div id="oerworldmap" style="height: 500px; width: 100%;"></div>',
  );
}

function oerworldmap_search($form, &$form_state) {

  $form['#method'] = 'GET';

  $term = isset($_GET['term']) ? $_GET['term'] : null;
  $filter = isset($_GET['filter']) ? $_GET['filter'] : null;

  $search_form = array(
    '#type' => 'textfield',
    '#default_value' => isset($term) ? $term : '',
  );

  $search_button = array(
    '#type' => 'submit',
    '#default_value' => 'Search',
  );

  $type_filter = array(
    '#type' => 'checkboxes',
    '#options' => array(
      'Organization' => 'Organization',
      'Person' => 'Person',
      'Service' => 'Service',
      'Project' => 'Project',
    ),
    '#title' => t('Restrict results to these types'),
    '#default_value' => isset($filter) ? array_keys($filter) : array(),
  );

  $form['term'] = $search_form;
  $form['submit'] = $search_button;
  $form['filter'] = $type_filter;

  if (!isset($term) || '' == $term) return $form;

  $endpoint_uri = 'http://' . variable_get('lde_api_host') . '/oer';
  $endpoints = ApplicationProfile::get(LDE_ENTITY_TYPE)->getEndpoints();
  $endpoint_params = $endpoints[$endpoint_uri];

  $query = new LinkedDataEntityFieldQuery();
  $query->addMetadata('endpoint', $endpoint_uri);
  $query->addMetadata('term', $term);
  foreach ($endpoint_params as $param => $value) {
    $query->addMetadata($param, $value);
  }

  if (isset($filter)) {
    $query->entityCondition('bundle', array_keys($filter));
  } else {
    $query->entityCondition('bundle', array('Organization', 'Service', 'Person', 'Project'));
  }

  $results = $query->execute();
  if ($results) foreach ($results as $result) {
    $view = entity_view(LDE_ENTITY_TYPE, array($result), 'full', null, false);
    $view += array(
      '#type' => 'fieldset'
    );
    $form[] = $view;
  }

  // Pagination
  $page = pager_find_page();
  $prev_link = l('<<', 'oerworldmap/search', array('query' => array(
    'page' => $page - 1,
    'term' => $term,
  )));
  $next_link = l('>>', 'oerworldmap/search', array('query' => array(
    'page' => $page + 1,
    'term' => $term,
  )));
  $pager = ($page > 0) ? "$prev_link $next_link" : $next_link;

  $form[] = array(
    '#type' => 'item',
    '#markup' => $pager,
  );

  return $form;
}

function oerworldmap_resource_add($type) {
  $entity = entity_get_controller(LDE_ENTITY_TYPE)->create(
    array('type' => $type, 'uri' => 'new')
  );
  return entity_form(LDE_ENTITY_TYPE, $entity);
}

function oerworldmap_resource_proxy() {

  $http_url = $_GET['uri'];
  $file_name = 'public://' . base64_encode($http_url);

  // Cache
  if (!file_exists($file_name)) {
    $http_options = array(
      'method' => 'GET',
      'headers' => array('Accept' => 'application/rdf+xml'),
    );
    $http_response = lde_http_request($http_url, $http_options);
    if (200 != $http_response->code) {
      return false;
    }
    file_put_contents($file_name, $http_response->data);
  }

  echo file_get_contents($file_name);

}

function oerworldmap_form_lde_form_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = 'oerworldmap_form_submit';
}

function oerworldmap_form_submit($form, &$form_state) {
}
