<?php

/**
 * Copyright 2014 Felix Ostrowski
 *
 * This file is part of ldap.
 *
 * ldap is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ldap is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ldap.  If not, see <http://www.gnu.org/licenses/>.
 */


/**
 * Implements hook_menu().
 */
function ldap_menu() {

  $items = array();

  $items['admin/config/ldap'] = array(
    'title' => 'Application Profile',
    'description' => 'Settings for the Application Profile module',
    'position' => 'left',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/ldap/update'] = array(
    'title' => 'Reload application profile',
    'description' => 'Reload bundles, fields and field instances from the application profile',
    'page callback' => 'ldap_update',
    'access arguments' => array('administer site configuration'),
  );

  return $items;

}

/**
 * Implements hook_entity_info_alter
 *
 * Sets the bundles for all entity types that are managed by an
 * application profile.
 *
 * @param  mixed  $entity_info
 */
function ldap_entity_info_alter(&$entity_info) {
  foreach (ApplicationProfile::getAll() as $entity_type => $ap) {
    $entity_info[$entity_type]['bundles'] = $ap->getBundles();
  }
}

function ldap_update() {
  foreach (ApplicationProfile::getAll() as $entity_type => $ap) {
    $ap->update();
    drupal_set_message("Application profile reloaded");
  }
  return array();
}

